name: le_spawn_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  dio: ^5.8.0+1
  get_it: ^8.0.3
  flutter_dotenv: ^5.2.1
  logger: ^2.5.0
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.5.2
  jwt_decoder: ^2.0.1
  equatable: ^2.0.7
  fluentui_system_icons: ^1.1.273
  go_router: ^13.2.0
  flutter_localizations:
    sdk: flutter
  outlined_text: ^1.0.1
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 
  assets:
    - assets/images/
    - .env
  fonts:
    - family: Acephimere
      fonts:
        - asset: assets/fonts/acephimere/acephimere.ttf
    - family: Grobold
      fonts:
        - asset: assets/fonts/grobold/grobold.ttf
